name: Bump

on:
  schedule:
    # Every 12 hours every day
    - cron: '0 */12 * * *'
  repository_dispatch:
    types:
      - bump

jobs:
  bump:
    strategy:
      matrix:
        formula:
          - apache-spark
          - benthos
          - confluent-platform
          - contentful-cli
          - evince
          - git-filter-repo
          - jetty
          - jetty-runner
          - ffmpeg
          - ilmbase
          - inko
          - jenkins
          - micro
          - newrelic-cli
          - opa
          - openexr
          - phpstan
          - sqlite
          - sslyze
          - stgit
          - yaegi
          - youtube-dl
          - wabt
    continue-on-error: true
    runs-on: macos-latest
    steps:
      - name: Bump formulae
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.TOKEN}}
          formula: ${{matrix.formula}}
          livecheck: true
